apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-books-database
  name: my-books-database
spec:
  selector:
    app: my-books-database
  ports:
    - name: "3306"
      port: 3306
      targetPort: 3306
