apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-books-ui
  name: my-books-ui
spec:
  type: LoadBalancer
  selector:
    app: my-books-ui
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80