apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-books-ui
  name: my-books-ui
spec:
  type: NodePort
  selector:
    app: my-books-ui
  ports:
    - name: 80-30000
      nodePort: 30000
      port: 80
      protocol: TCP
      targetPort: 80