apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: my-books-service-claim0
  name: my-books-service-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
