apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-books-service
  name: my-books-service
spec:
  selector:
    app: my-books-service
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 8080