apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-books-service
  name: my-books-service
spec:
  type: LoadBalancer
  selector:
    app: my-books-service
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080